### ISSUE TITLE
How are multiple  _config.yml maintained 

### ISSUE THREAD

**Issue by Sabryr** [hpc-carpentry/hpc-intro#173] opened 2020-07-29 08:44 UTC
At the moment I need to stash my _config.yml during push/pulls. Wondering how others are handling it (may be there is an elegant way) . Then what is the use of (where is it useed),
_includes/snippets_library/ComputeCanada_Graham_slurm/_config_options.yml

IMO, most of the _config.yml could be transferred to snippets as well

**Comment by reid-a** [comment] 2020-07-29 14:00
I believe the thinking behind the current design is that the 
_config.yml is a convenient central location for variables that
any given site-specific lesson instance will certainly need.

  That it would require customization is OK, in this model, 
because it's not conceptually different from things like the 
venue location and date and other instance-specific data you'd 
have to customize anyways before publishing an announcement.

  But on reflection, it's true that site data is longer-lived
than instance data.  On the other hand, the items you'll need
(but not their values) are common across all sites, so what
we really want is to centralize the structure of the configuraiton,
but distribute the site-specific values.

  Not sure how to do that.

 				-- A. 

On Wed, Jul 29, 2020 at 01:44:43AM -0700, Sabry Razick wrote:
> At the moment I need to stash my _config.yml during push/pulls. Wondering how
> others are handling it (may be there is an elegant way) . Then what is the use
> of (where is it useed),
> _includes/snippets_library/ComputeCanada_Graham_slurm/_config_options.yml
> 
> IMO, most of the _config.yml could be transferred to snippets as well
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 
Dr. Andrew C. E. Reid
Physical Scientist, Computer Operations Administrator
Center for Theoretical and Computational Materials Science
National Institute of Standards and Technology, Mail Stop 8555
Gaithersburg MD 20899 USA
andrew.reid@nist.gov

**Comment by tkphd** [comment] 2020-07-29 14:33
Excellent point, @Sabryr, and one that's important for us all to be aware of. You're right that, at this point, changes to `_config.yml` will get clobbered when you `git pull` from hpc-carpentry. The purpose of the `_config_options.yml`s in the snippet library is to maintain your site-specific settings, so that they can be restored to `_config.yml` when it's overwritten, or for someone attempting to duplicate (or branch off from) your site to get those settings right. 

From a technical standpoint, the problem is that Jekyll does not admit *variables* in `_config.yml`: everything must be hard-coded. There are alternative ways to build the tree of variables, but ultimately, they all have to be hard-coded, or in hard-coded paths. 

I'm basing this on the way Jekyll builds my [résumé](https://github.com/tkphd/resume). The layout is specified in [resume.html](https://github.com/tkphd/resume/blob/gh-pages/_layouts/resume.html), populated through loops and conditionals with variables matching the pattern `site.data.<section>.<name>`. These variables are defined in YAML files under the [_data](https://github.com/tkphd/resume/tree/gh-pages/_data) folder, each containing hard-coded items. There are no variables in this chain: if I wanted to serve two résumés from this single repository, I would either have to overwrite `_config.yml` and everything under `_data`, or else create a subdirectory for each identity in `_data` and rewrite every instance of `site.data.<section>.<name>` with `site.data.identity.<section>.<name>` to get Jekyll to build the intended site.

Either way, files that are tracked by Git will get changed. The intent here is to limit the impact to just one file, `_config.yml`, and provide developers a place to maintain an archival copy of site settings in case it gets clobbered (that's `_config_options.yml`).

I hope that clarifies, even though it's not much help alleviating the workload. I've still only explored the surface of the iceberg known as Jekyll, so if there are advanced features that would allow us to switch content without overwriting anything, or perhaps by writing just one parameter in `_config.yml`, I would be very interested to try it out.

**Comment by tkphd** [comment] 2020-07-29 14:35
At the moment, I believe we need to document how site-specialization of `_config.yml` is handled, before exploring trickier Jekyll usage. What would be the right place -- `index.md`?

**Comment by Sabryr** [comment] 2020-07-29 14:48
Thank you both. As we lack a elegant method. 

I tried with sim-links:
i.e. have my _config.yml under  _includes/snippets_library/SIGMA2_Norway_slurm/ and replace the _config.yml with a link to this.

 ln -s  _includes/snippets_library/SIGMA2_Norway_slurm/_config.yml _config.yml 

If we ignore the simlink in .gitignore this would be seamless.

**Comment by tkphd** [comment] 2020-07-30 16:35
Thanks for testing, @Sabryr. Unfortunately, excluding `_config.yml` from Git would block continuous integration -- essentially, we could not test that the site builds. And, since symbolic links checked in to Git are not cross-platform compatible, this is not a viable solution.

If symlinks work for you, for now, that's cool -- and possibly worth documenting as a potential solution for local builds of the site. I'm not sure how the GitHub & GitLab pages services react to symlinked config files, but it just might work.

**Comment by tkphd** [comment] 2020-07-30 17:05
Ah-ha! You can give Jekyll [multiple config files](https://jekyllrb.com/docs/configuration/options/#build-command-options) as a comma-separated list, and settings in later files overwrite earlier ones! 

```bash
$ jekyll --config _config.yml,_includes/snippet_library/SIGMA2_Norway_slurm/_config.yml serve
```

So, a portable solution would use an environment variable, empty by default, containing the config files you want:
```bash
$ export JEKYLL_CONFIG=_config.yml,_includes/snippet_library/SIGMA2_Norway_slurm/_config.yml
$ jekyll ${JEKYLL_CONFIG} serve
```

If this is *not* set, e.g. on Travis/GitHub/GitLab, it will use the default `_config.yml` for Graham. If the variable *is* set, and includes a second file, the Graham-specific pieces will get overwritten, and the website should build with your cluster details instead.

Setting an environment variable on Windows may not be the easiest thing. Perhaps manually specifying the parameter is best, or at least, ought to be the solution we highlight in the documentation. Anyway, I'll start testing this. Thanks again for the prompt, @Sabryr.

**Comment by tkphd** [comment] 2020-07-30 17:16
Confirmed locally: this works!

**Comment by Sabryr** [comment] 2020-07-31 06:51
@tkphd thank you this is really helpful. This will not help the push/pull between my folk and the main repo though. This is not a showstopper, I just wanted to know whether there is an elegant way to do this.

**Comment by tkphd** [comment] 2020-07-31 16:28
If "your folk" can set the `SITE_CONFIG` environment variable, then this approach could be adopted and would resolve the push & pull between the repositories, I believe. Is there a technical barrier that I'm missing?

**Closed** 2020-08-07 09:04 UTC
